@echo off
echo Initializing Git repository...
git init
echo Adding remote repository...
git remote add origin https://github.com/iir-24-25/projet-devops-g7-xg7_g4.git
echo Adding files to staging...
git add .
echo Creating initial commit...
git commit -m "Initial commit"
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause 